# Generated by Django 5.0.7 on 2024-07-25 11:52

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.TextField(verbose_name='title english')),
                ('title_th', models.TextField(blank=True, verbose_name='title thai')),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='content english')),
                ('content_th', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='content thai')),
                ('image', models.ImageField(upload_to='news')),
                ('order', models.PositiveIntegerField(default=0)),
                ('publish', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'news',
                'ordering': ('-order',),
            },
        ),
    ]
