# Generated by Django 2.2.4 on 2019-08-09 11:10

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190809_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='code_en',
        ),
        migrations.RemoveField(
            model_name='news',
            name='code_th',
        ),
        migrations.AlterField(
            model_name='news',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_th',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=''),
        ),
    ]
