# Generated by Django 2.2.4 on 2019-08-10 03:42

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20190809_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='content english'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_th',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='content thai'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_en',
            field=models.TextField(verbose_name='title english'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_th',
            field=models.TextField(blank=True, verbose_name='title thai'),
        ),
    ]
