# Generated by Django 2.2.4 on 2019-10-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20190810_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(null=True, upload_to='news'),
        ),
        migrations.DeleteModel(
            name='NewsImage',
        ),
    ]
