# Generated by Django 5.0.7 on 2024-07-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('frd', 'Fire Doors'), ('fdc', 'Fire Dampers'), ('fsd-ul', 'Fire & Smoke Dampers'), ('ddp', 'Duct Dampers'), ('ds', 'Duct Silencers'), ('aol', 'Air Outlets'), ('dhw', 'Door Hardware')], default='frd', max_length=6)),
                ('document_type', models.CharField(choices=[('catg', 'Catalog'), ('cert', 'Certificate'), ('inst', 'Installation')], default='catg', max_length=5)),
                ('title_en', models.CharField(max_length=255, verbose_name='title english')),
                ('title_th', models.CharField(blank=True, max_length=255, verbose_name='title thai')),
                ('image', models.ImageField(blank=True, upload_to='document')),
                ('doc_en', models.FileField(upload_to='document', verbose_name='document english')),
                ('doc_th', models.FileField(blank=True, upload_to='document', verbose_name='document thai')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
