# Generated by Django 2.2.4 on 2019-08-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('catg', 'Catalog'), ('inst', 'Installation'), ('cert', 'Certificate')], default='catg', max_length=5),
        ),
        migrations.AddField(
            model_name='document',
            name='product_type',
            field=models.CharField(choices=[('frd', 'Fire Doors'), ('fdc', 'Fire Dampers'), ('ddp', 'Duct Dampers'), ('ds', 'Duct Silencers'), ('aol', 'Air Outlets'), ('dhw', 'Door Hardware')], default='frd', max_length=5),
        ),
    ]
