# Generated by Django 2.2.4 on 2019-08-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_auto_20190809_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_th',
            field=models.FileField(blank=True, upload_to='document'),
        ),
    ]
