# Generated by Django 2.1.14 on 2023-05-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0007_auto_20191031_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('catg', 'Catalog'), ('cert', 'Certificate'), ('inst', 'Installation')], default='catg', max_length=5),
        ),
        migrations.AlterField(
            model_name='document',
            name='product_type',
            field=models.CharField(choices=[('frd', 'Fire Doors'), ('fdc', 'Fire Dampers'), ('fsd-ul', 'Fire & Smoke Dampers'), ('ddp', 'Duct Dampers'), ('ds', 'Duct Silencers'), ('aol', 'Air Outlets'), ('dhw', 'Door Hardware')], default='frd', max_length=6),
        ),
    ]
