# Generated by Django 2.1.14 on 2023-05-12 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0008_auto_20230512_1744'),
        ('document', '0008_auto_20230512_1059'),
    ]

    operations = [
    ]
