# Generated by Django 2.2.4 on 2019-08-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_choice', models.CharField(choices=[('frd', 'Fire Doors'), ('fdc', 'Fire Dampers'), ('ddp', 'Duct Dampers'), ('ds', 'Duct Silencers'), ('aol', 'Air Outlets'), ('dhw', 'Door Hardware')], default='frd', max_length=3)),
                ('title_en', models.CharField(max_length=255)),
                ('title_th', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='product')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
