# Generated by Django 5.0.7 on 2024-07-25 11:52

import ckeditor.fields
import sorl.thumbnail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('frd', 'Fire Doors'), ('fdc', 'Fire Dampers'), ('fsd-ul', 'Fire & Smoke Dampers'), ('ddp', 'Duct Dampers'), ('ds', 'Duct Silencers'), ('aol', 'Air Outlets'), ('dhw', 'Door Hardware')], default='frd', max_length=10)),
                ('title_en', models.CharField(max_length=255, verbose_name='title english')),
                ('title_th', models.CharField(blank=True, max_length=255, verbose_name='title thai')),
                ('desc_en', ckeditor.fields.RichTextField(blank=True, default='', verbose_name='description english')),
                ('desc_th', ckeditor.fields.RichTextField(blank=True, default='', verbose_name='description thai')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='product')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
