# Generated by Django 2.2.4 on 2019-08-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20190809_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desc_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc_th',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_th',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
