# Generated by Django 2.2.4 on 2019-08-09 10:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20190809_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desc_en',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc_th',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
    ]
