# Generated by Django 2.2.4 on 2019-10-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20190810_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('frd', 'Fire Doors'), ('fdc', 'Fire Dampers'), ('fsd-ul', 'Fire & Smoke Dampers'), ('ddp', 'Duct Dampers'), ('ds', 'Duct Silencers'), ('aol', 'Air Outlets'), ('dhw', 'Door Hardware')], default='frd', max_length=3),
        ),
    ]
