# Generated by Django 2.1.14 on 2019-11-11 09:46

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20191026_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='product'),
        ),
    ]
