# Generated by Django 5.0.7 on 2024-07-25 11:52

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', ckeditor.fields.RichTextField(verbose_name='title english')),
                ('title_th', ckeditor.fields.RichTextField(blank=True, default='', verbose_name='title thai')),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='content english')),
                ('content_th', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='content thai')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'finance',
                'ordering': ('-order',),
            },
        ),
    ]
