# Generated by Django 2.2.4 on 2019-08-09 09:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='content_en',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
