# Generated by Django 2.2.4 on 2019-08-09 10:31

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20190809_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='content_th',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=''),
        ),
    ]
