# Generated by Django 2.2.4 on 2019-08-10 03:42

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20190809_1031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finance',
            options={'ordering': ('-order',), 'verbose_name_plural': 'finance'},
        ),
        migrations.AlterField(
            model_name='finance',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='content english'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='content_th',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='content thai'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='title_en',
            field=ckeditor.fields.RichTextField(verbose_name='title english'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='title_th',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='title thai'),
        ),
    ]
