# Generated by Django 5.0.7 on 2024-07-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255, verbose_name='title english')),
                ('title_th', models.CharField(blank=True, max_length=255, verbose_name='title thai')),
                ('country', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=10)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='project')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('-order',),
            },
        ),
    ]
