# Generated by Django 2.2.4 on 2019-08-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255)),
                ('title_th', models.CharField(max_length=255)),
                ('desc_en', models.TextField(default='')),
                ('desc_th', models.TextField(default='')),
                ('country', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='project')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
