# Generated by Django 2.2.4 on 2019-08-09 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20190809_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='desc_en',
        ),
        migrations.RemoveField(
            model_name='project',
            name='desc_th',
        ),
    ]
