# Generated by Django 2.2.4 on 2019-08-10 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20190809_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title_en',
            field=models.CharField(max_length=255, verbose_name='title english'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title_th',
            field=models.CharField(blank=True, max_length=255, verbose_name='title thai'),
        ),
    ]
