# Generated by Django 2.2.4 on 2019-10-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20190810_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='company',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
