# Generated by Django 2.2.6 on 2019-10-31 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20191026_0810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-order',)},
        ),
    ]
